title: Edinburgh Napier COVID Dashboard Project
description: Making better public health decisions
logo: /assets/images/logo.png
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
exclude:
  - README.md
